drop table mascota_revision;
drop table mascota_solicitud;
drop table historico_status_mascota;
drop table donado;
drop table nacido;
drop table mascota;
drop table cliente;
drop table status;
drop table tipo;
drop table oficina;
drop table clinica;
drop table refugio_web;
drop table refugio;
drop table veterinario;
drop table gerente;
drop table administrativo;
drop table centro_operativo;
drop table empleado_titul